In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("datasets/2017_2018_initial_processed.csv")
df.head(10)

c:\users\aidan\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,CASE_STATUS,VISA_CLASS,EMPLOYER_NAME,EMPLOYER_ADDRESS,EMPLOYER_CITY,EMPLOYER_STATE,EMPLOYER_POSTAL_CODE,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_CODE,...,PW_SOURCE_YEAR,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_CITY,WORKSITE_COUNTY,WORKSITE_STATE,WORKSITE_POSTAL_CODE
0,CERTIFIED-WITHDRAWN,H-1B,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,",",POSTDOCTORAL ASSOCIATE,15-2041,...,2015.0,58032.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
1,CERTIFIED-WITHDRAWN,H-1B,MASSACHUSETTS INSTITUTE OF TECHNOLOGY (MIT),77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,",",ASSISTANT PROFESSOR,25-1031,...,2016.0,95600.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX COUNTY,MA,02139
2,CERTIFIED-WITHDRAWN,H-1B,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,",",POSTDOCTORAL ASSOCIATE,19-2012,...,2016.0,60400.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
3,CERTIFIED-WITHDRAWN,H-1B,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,",",RESEARCH SCIENTIST,19-2042,...,2016.0,65000.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
4,CERTIFIED-WITHDRAWN,H-1B,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,MA,02139,",",POSTDOCTORAL ASSOCIATE,17-2131,...,2016.0,49383.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
5,CERTIFIED-WITHDRAWN,H-1B,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",9440 SANTA MONICA BLVD,BEVERLY HILLS,CA,90210,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,13-1121,...,2016.0,45200.00,0.0,Year,N,N,BEVERLY HILLS,LOS ANGELES,CA,90210
6,WITHDRAWN,H-1B,IBM INDIA PRIVATE LIMITED,3039 CORNWALLIS ROAD,DURHAM,NC,27709,",",SENIOR DEVELOPER,15-1131,...,2017.0,81837.00,0.0,Year,N,N,DOWNERS GROVE,DUPAGE,IL,60515
7,WITHDRAWN,H-1B,IBM INDIA PRIVATE LIMITED,3039 CORNWALLIS ROAD,DURHAM,NC,27709,",",SENIOR SOFTWARE ENGINEER,15-1131,...,2017.0,81499.00,0.0,Year,N,N,WHITEHOUSE STATION,HUNTERDON,NJ,08889
8,WITHDRAWN,H-1B,BTREE SOLUTIONS INC,570 HERNDON PARKWAY,HERNDON,VA,20170,",",COMPUTER SYSTEMS ANALYST,15-1121,...,2017.0,76000.00,0.0,Year,Y,N,COLUMBUS,FRANKLIN,OH,43214
9,CERTIFIED-WITHDRAWN,H-1B,"WALTER ASSOCIATES, INCORPORATED","100 E. MICHIGAN AVENUE, SUITE 200",SALINE,MI,48176,"UBHI, ARVINDER",ASSOCIATE,15-1132,...,2014.0,88381.32,0.0,Year,N,N,SALINE,WASHTENAW,MI,480176

In [2]:
df["CASE_STATUS"].unique()

array(['CERTIFIED-WITHDRAWN', 'WITHDRAWN', 'CERTIFIED', 'DENIED'],
      dtype=object)

In [3]:
df = df[df["CASE_STATUS"] != 'WITHDRAWN']

In [4]:
df["CASE_STATUS"].replace('CERTIFIED-WITHDRAWN', 'CERTIFIED', inplace=True)

Agent attorney name seems to be filled with , to avoid na values

In [5]:
df_agent = df[df["AGENT_ATTORNEY_NAME"] == ","]
df_agent["AGENT_ATTORNEY_NAME"].count()

408455

In [6]:
df = df.drop(["AGENT_ATTORNEY_NAME"], axis=1)

In [7]:
df.corr()

,TOTAL_WORKERS,NEW_EMPLOYMENT,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,PREVAILING_WAGE,PW_SOURCE_YEAR,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO
TOTAL_WORKERS,1.000000,0.776024,0.429969,0.310912,0.110236,0.402492,0.420653,0.005485,0.001999,0.001193,0.127073
NEW_EMPLOYMENT,0.776024,1.000000,0.033084,0.015999,0.021940,0.031119,0.025609,-0.000683,0.000448,-0.026551,0.075571
CONTINUED_EMPLOYMENT,0.429969,0.033084,1.000000,0.094878,0.072999,0.176272,0.150729,0.006879,0.001244,0.026357,0.056440
CHANGE_PREVIOUS_EMPLOYMENT,0.310912,0.015999,0.094878,1.000000,0.109160,0.156432,0.101484,0.004191,0.002024,0.011904,0.090575
NEW_CONCURRENT_EMPLOYMENT,0.110236,0.021940,0.072999,0.109160,1.000000,0.072857,0.045645,-0.011162,0.003564,-0.061775,0.026163
CHANGE_EMPLOYER,0.402492,0.031119,0.176272,0.156432,0.072857,1.000000,0.172777,0.010230,0.002496,0.046781,0.067335
AMENDED_PETITION,0.420653,0.025609,0.150729,0.101484,0.045645,0.172777,1.000000,0.003065,0.000491,0.004084,0.060219
PREVAILING_WAGE,0.005485,-0.000683,0.006879,0.004191,-0.011162,0.010230,0.003065,1.000000,0.002186,0.148728,0.045769
PW_SOURCE_YEAR,0.001999,0.000448,0.001244,0.002024,0.003564,0.002496,0.000491,0.002186,1.000000,0.007017,-0.002478
WAGE_RATE_OF_PAY_FROM,0.001193,-0.026551,0.026357,0.011904,-0.061775,0.046781,0.004084,0.148728,0.007017,1.000000,0.205263
WAGE_RATE_OF_PAY_TO,0.127073,0.075571,0.056440,0.090575,0.026163,0.067335,0.060219,0.045769,-0.002478,0.205263,1.000000

In [13]:
df.dtypes

CASE_STATUS                    object
VISA_CLASS                     object
EMPLOYER_NAME                  object
EMPLOYER_ADDRESS               object
EMPLOYER_CITY                  object
EMPLOYER_STATE                 object
EMPLOYER_POSTAL_CODE           object
JOB_TITLE                      object
SOC_CODE                       object
SOC_NAME                       object
NAICS_CODE                     object
TOTAL_WORKERS                   int64
NEW_EMPLOYMENT                  int64
CONTINUED_EMPLOYMENT            int64
CHANGE_PREVIOUS_EMPLOYMENT      int64
NEW_CONCURRENT_EMPLOYMENT       int64
CHANGE_EMPLOYER                 int64
AMENDED_PETITION                int64
FULL_TIME_POSITION             object
PREVAILING_WAGE               float64
PW_UNIT_OF_PAY                 object
PW_SOURCE                      object
PW_SOURCE_YEAR                float64
WAGE_RATE_OF_PAY_FROM         float64
WAGE_RATE_OF_PAY_TO           float64
WAGE_UNIT_OF_PAY               object
H1B_DEPENDENT                  object
WILLFUL_VIOLATOR               object
WORKSITE_CITY                  object
WORKSITE_COUNTY                object
WORKSITE_STATE                 object
WORKSITE_POSTAL_CODE           object
dtype: object

In [11]:
from sklearn.decomposition import PCA
pca = PCA()

In [12]:
pca.fit(df)

ValueError: could not convert string to float: '95054-1214'